version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql_test
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - 30001:3306
    expose:
      - 30001
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - test
      
  apache:
    build: ./apache
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - ./apache/src/:/var/www/html  
    depends_on:
      - db 
    networks:
      - test

networks:
  test:

volumes:
  my-db:
    driver: local